---
title: "Week 7 Class Problems"
author: "John Vinson"
date: "9/26/2017"
output: pdf_document
---

1. Find a function $f$ and a number $a$ such that

\begin{equation}
lim_{h \to 0} \frac{(2+h)^6 - 64}{h} = f^{'}(a)
\end{equation}

\vspace{12 pt}

*From the definition of a derivative,*

\begin{equation}
lim_{h \to 0} \frac{f(x+h) - f(x)}{h} = f^{'}(x)
\end{equation}

*We can see that the function is $f(x) = x^6$ and $a=2$.*

2. Suppose that the number of calories of heat required to raise 1 gram of water (or ice) from -40$^{\circ}C$ to x$^{\circ}C$ is given by

\begin{equation}
f(x) = \begin{cases}
 \frac{1}{2}x+20 & \text{if $-40 \leq x < 0$} \\
 x + 100 & \text{if $0 \leq x$} \\
\end{cases}
\end{equation}

Is the function continuous $\forall x \in [-40,\infty)$? What happens to water at 0$^{\circ}C$ that account for the behavior of the function at 0 $^{\circ}C$?

*The function is not contiuous $\forall x \in [-40,\infty)$.  At $x=0$, *

\begin{equation}
lim_{x \to 0^-} \frac{1}{2}x+20 = 20
\end{equation}

*and *

\begin{equation}
lim_{x \to 0^+} x+100 = 100
\end{equation}

*Therefore, since the $lim_{x \to 0^-} f(x) \neq lim_{x \to 0^+} f(x)$ the function is not continuous at $x=0$. At 0$^{\circ}C$ water goes through a phase change from liquid to solid. *

\vspace{12pt}

3. Find the asymptotes of the graph of $f(x) = \frac{4-x}{3+x}$ and use them to sketch the graph and the graph of $f^{'}$. Find $f^{'}$ and graph it in R.

*We can see that the function is not continuous at $x=-3$. So there may be an asymptote there. We need to look at the limits at $x=-3$*

\begin{equation}
lim_{x \to -3^-} \frac{4-x}{3+x} =  \frac{lim_{x \to -3^-} 4-x}{lim_{x \to -3^-} 3+x} = \frac{7}{0_-} = -\infty
\end{equation}

*and *

\begin{equation}
lim_{x \to -3^+} \frac{4-x}{3+x} =  \frac{lim_{x \to -3^+} 4-x}{lim_{x \to -3^+} 3+x} = \frac{7}{0_+} = +\infty
\end{equation}

*What about the behavior as $x \to -\infty$ and $x \to +\infty$.*

\begin{equation}
lim_{x \to -\infty} \frac{4-x}{3+x} \text{ and } lim_{x \to +\infty} \frac{4-x}{3+x}
\end{equation}

*To calculate these, we have to follow L'Hospital's Rule which says that if we have*

\begin{equation}
lim_{x \to a} \frac{f(x)}{g(x)} = \frac{0}{0} \text{ or } \frac{\pm \infty}{\pm \infty} 
\end{equation}

*with a as any real number or $\pm \infty$. We can have*

\begin{equation}
lim_{x \to a} \frac{f(x)}{g(x)} = lim_{x \to a} \frac{f^{'}(x)}{g^{'}(x)}
\end{equation}

*Using this, we have*

\begin{equation}
lim_{x \to -\infty} \frac{4-x}{3+x} = lim_{x \to -\infty} \frac{-x}{x} = -1 \text{ and } lim_{x \to +\infty} \frac{-x}{x} = -1 
\end{equation}

*Overall, there are two/three asymptotes. *

*At $x=-3$ where from the left $f(x) \to -\infty$ and from the right $f(x) \to +\infty$.*

*As $x \to -\infty$, $f(x) \to -1$ from the bottom (as at $x \to -3^- = -\infty$).*

*As $x \to +\infty$, $f(x) \to -1$ from the top (as at $x \to -3^+ = +\infty$).*

```{r, echo=TRUE}
n.3 = function(x){return((4-x)/(3+x))}

x.seq = seq(-50, 50)

plot(x.seq, n.3(x.seq), type="l", xlab="x", ylab="f(x)")
```

\vspace{12pt}

4. A bacteria culture contains 200 cells initially and grows at a rate proportional to its size. After half an hour the population has increased to 360 cells. 

- Find the number of bacteria after t hours.
- Find the number of bacteria after 4 hours.
- Find the rate of growth after 4 hours
- When will the population reach 10,000?

Since we are given that the population grows at a rate that is proportional to its current size, we can use the model

\begin{equation}
N(t) = N_0 e^{rt}
\end{equation}

what we do not know and need to find is r. We can rearrange the equation to

\begin{equation}
r = \frac{ln(\frac{N_t}{N_0})}{t}
\end{equation}

Using the information from the problem

\begin{equation}
r = \frac{ln(\frac{360}{200})}{0.5} = 1.175573
\end{equation}
\vspace{12pt}

Which means our model is

\begin{equation}
N(t) = 200 e^{1.175573 * t}
\end{equation}

After 4 hours, 

\begin{equation}
N(4) = 200 e^{1.175573 * 4} \approx 22040
\end{equation}

To find the rate of growth, we need to take a derivative

\begin{equation}
N^{'}(t) = 1.175573 * 200  e^{1.175573 * t} = r * N(t)
\end{equation}

So, if we set t=4,

\begin{equation}
N^{'}(4) = r * N(t) = 1.175573 * 22040 \approx 25910 \text{ bacteria/hour}
\end{equation}

To find the time when the population will reach a certain size we need to rearrange $N(t)$

\begin{align}
N(t) =& N_0 e^{rt}\\
t =& \frac{ln(\frac{N(t)}{N_0})}{r}
\end{align}

We need to determine when the population reaches 10000 individuals.

\begin{equation}
t = \frac{ln(\frac{10000}{200})}{1.175573} \approx 3.33 \text{ hours}
\end{equation}



